spring.application.name=gestionasistencia

# Configuración de MongoDB Atlas
# SUSTITUYE <usuario>, <password> y el cluster por tus datos reales de Atlas
spring.data.mongodb.uri=mongodb+srv://admin_profesor:admin@asistenciadam.tr1xlor.mongodb.net/asistencias_db?appName=AsistenciaDAM

# Para ver las consultas en consola (útil para depurar)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG